### ISSUE TITLE
"Taiwan, Province of China" to "Taiwan"

### ISSUE THREAD

**Issue by thomasdziedzic** [carmen-ruby/carmen#178]
Looks like https://github.com/jim/carmen/pull/38 got lost in a release a couple of years ago

references:
http://meta.stackexchange.com/questions/170143/taiwan-is-not-a-province-of-china
https://github.com/square/shuttle/pull/32
http://www.koziarski.net/archives/2008/9/24/countries-and-controversies/

**Comment by dshack** [comment]
:+1:

**Comment by ecbypi** [comment]
Is it a matter of the `locale/base/world.yml` file being out of date or is the wrong value coming through when using the gem?  If the former, the information in `locale/base` is auto-generated; `locale/overlay` contains the corrected name.  Or is that name incorrect?

**Comment by thomasdziedzic** [comment]
looking at the source at:
https://github.com/jim/carmen/blob/master/script/update_data.rb#L61

looks like the iso has the wrong value so it's not a matter of regenerating ```locale/base/world.yml```. The wrong value is just coming through with the gem.

Thanks for looking into this!

**Comment by thomasdziedzic** [comment]
I was able to fix this by creating a file under ```config/locales``` in my rails app (since we're also using carmen-rails:

```
en:
  world:
    tw:
      common_name: Taiwan
      name: Taiwan
      official_name: Taiwan
```

**Comment by swcraig** [comment]
I know this is super old.
This is fixed on master. We are working on getting a new release (1.1.0) out soon. Thanks for reporting.
