### ISSUE TITLE
how to delete subregion if it's not exist~?

### ISSUE THREAD

**Issue by jcsky** [carmen-ruby/carmen#202]
ex: some subregion was merged to other subregion, how to delete it~?!

**Comment by jcsky** [comment]
some subregion in taiwan is fail, but I don't know how to delete it, like tainan or taipei district

**Comment by swcraig** [comment]
Hi @jcsky, thanks for opening an issue. I am going to close this since it is stale. If this is still a problem for you, please open another issue with some code examples to go along with it.
