### ISSUE TITLE
UK province and states

### ISSUE THREAD

**Issue by matt-hu** [carmen-ruby/carmen#208]
Did anyone know that UK uses county instead of state/province. Some UK customers are complaining about this when we are using Carmen as the source of countries and provinces.

**Comment by swcraig** [comment]
Thanks for reporting. Going to close this as stale. We pull the data from the ISO and take whatever "type" they say it is.

**Comment by MatthewKennedy** [comment]
The UK ISO data is using British cities mixed in with British Counties...
Lancashire (County), Bradford (City), Essex(County), Manchester (City), Leeds (City).

This list is not what would be seen in a drop-down selector for State or Region in an online checkout for example.
