### ISSUE TITLE
Puerto Rico vs US Virgin Islands - inconsistent country/subregion representation?

### ISSUE THREAD

**Issue by IntractableQuery** [carmen-ruby/carmen#214]
In issue #120 some precedent was set to remove `PR` from the list of "countries" since it was already a US subregion.

However, this results in an interesting inconsistency versus how US Virgin Islands are represented;

Both are a part of the US:

<pre>
> Carmen::Country.coded('us').subregions.coded('vi')
=> <#Carmen::Region name="Virgin Islands" type="outlying area">

> Carmen::Country.coded('us').subregions.coded('pr')
=> <#Carmen::Region name="Puerto Rico" type="outlying area">
</pre>

But, not both get to be world-level "countries":

<pre>
> Carmen::Country.coded('vi')
=> <#Carmen::Country name="Virgin Islands, U.S.">

> Carmen::Country.coded('pr')
=> nil
</pre>

Looking at wikipedia and https://www.iso.org/obp/ui/#search, `PR` is a recognized "country" level code.  Should the change prompted by issue #120 be reverted, and it be allowed that the same geographical region can live both at country and subregion level?

**Comment by swcraig** [comment]
Hi @IntractableQuery, thank you for bringing this up.

I tend to agree with you. [Puerto Rico being an unincorporated territory of the United States](https://en.wikipedia.org/wiki/Unincorporated_territories_of_the_United_States) is irrelevant to whether we should treat 'PR' as a country code. We should not be making "calls" of what should or should not be considered a country code, we should follow the [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) standard.

If developers disagree with changes like this they can [follow the steps in the README](https://github.com/carmen-ruby/carmen#disabling-elements) to modify their data.

I would be interested in hearing @gr8bit's thoughts.

**Comment by gr8bit** [comment]
I completely agree - in my opinion the Carmen gem should be just a mirror of the ISO data, not a layer where changes are applied to the ISO standards. But if someone chooses to do so, (s)he have all the necessary tools at hand to change that data with the guide you linked.
