### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by Sayanc93** [carmen-ruby/carmen#220]
I was trying to use `typed` method defined here https://github.com/jim/carmen/blob/master/lib/carmen/region_collection.rb#L25.

But failed to find the method in the latest carmen version. I think there was no version release prior to that change; I see the last version release was in March, 2015 and the change went into Master in December, 2015.
https://github.com/jim/carmen/commit/1605b43a4dc5df60a5dcb6ddd98fd1b595e0375c

https://rubygems.org/gems/carmen

I believe bumping the version would benefit all.

Cheers.

**Comment by panozzaj** [comment]
Thank you for working on this project, we are using it for a nice state list in our project. Hoping this helps, I just ran into the exact same problem (trying to use the `typed` method as the latest version of documentation suggests is possible.) We are running 1.0.2, the most recently released version of the gem.

**Comment by oshanz** [comment]
actually, the `alpha_3_coded` function couldn't find from master branch either? where is it?

**Comment by swcraig** [comment]
We are working on getting a new version (1.1.0) out soon. Thanks for checking in.
