### ISSUE TITLE
1.0.3 Release Status

### ISSUE THREAD

**Issue by swcraig** [carmen-ruby/carmen#226]
Hello Carmen team!

I see in the CHANGELOG that there is a pending 1.0.3 release that is ~2 years old. Will there be a move anytime soon to push this? 

I notice that there is another issue also asking about the release status... the people are in suspense!

Thank you for your all of your work!

**Comment by gr8bit** [comment]
There are also quite a lot of PRs floating around... @jim, would you like some help in maintaining Carmen?

**Comment by jim** [comment]
@gr8bit Yes, I could use help. It is in urgent need of some new maintainer(s), so let me know if you are interested.

**Comment by gr8bit** [comment]
As we use Carmen in our own projects, I'd be glad to help out. It would be great if you found the time to give directions when it comes to new features or PRs touching core aspects of Carmen though. :)

**Comment by swcraig** [comment]
@jim I am also interested in helping out here. 

I am in the same boat as @gr8bit, any input on PRs touching core aspects of Carmen would be appreciated.

**Comment by gr8bit** [comment]
I'm currently updating the scripts used for importing the latest data (format changed). I hope to getting it done this week and report back to you asap :)

**Comment by swcraig** [comment]
We have the ball rolling for this.
