### ISSUE TITLE
Kenya's provinces were replaced by a system of counties in 2013.

### ISSUE THREAD

**Issue by TylerRick** [carmen-ruby/carmen#227]
According to https://en.wikipedia.org/wiki/Provinces_of_Kenya
> Kenya's provinces were replaced by a system of counties in 2013.

https://en.wikipedia.org/wiki/ISO_3166-2:KE confirms that they are "former" provinces.

Carmen should be updated to include the 47 counties listed under https://en.wikipedia.org/wiki/ISO_3166-2:KE.

**Comment by swcraig** [comment]
Thanks for reporting. PRs are welcome!

**Comment by swcraig** [comment]
Fixed in #252.
