### ISSUE TITLE
France's 27 regions were reduced to 18 in 2016

### ISSUE THREAD

**Issue by TylerRick** [carmen-ruby/carmen#228]
According to https://en.wikipedia.org/wiki/Regions_of_France
> In 2016 what had been 27 regions was reduced to 18.
> France is divided into 18 administrative regions, including 13 metropolitan regions and 5 overseas regions.

You can find the list on https://en.wikipedia.org/wiki/ISO_3166-2:FR (but it also contains former regions which should *not* be included, so only select the 13 metropolitan regions plus the 5 overseas regions.)

**Comment by swcraig** [comment]
Thanks for reporting. I think this is resolved now. There are 26 subregions total, including the "Depdendency and overseas territorial collectivities", "Overseas departments", and "Metropolitan regions".

**Comment by TylerRick** [comment]
Awesome, thanks!
