### ISSUE TITLE
New Maintenance Plan

### ISSUE THREAD

**Issue by jim** [carmen-ruby/carmen#229]
I've created a new organization for this gem (and its neglected sibling, carmen-rails.) It is my goal to completely step away from this project in the nearish future.

Most of the work that needs to be done is triaging issues and pull requests and performing data updates on a regular interval.

* Updating the data is done with [this script](https://github.com/carmen-ruby/carmen/blob/master/script/update_data.rb).
* I would suggest moving to some kind of calendar-based release schedule to incorporate bug fixes, translation submissions, and upstream data changes. Perhaps every 3 or 6 months?

@gr8bit and @swcraig have volunteered to oversee the maintenance of this project. I will be in touch with folks to grant them access to the RubyGem projects for release.

@dainmiller @jtapia @ecbypi @j15e Thanks for helping out with this project in the past. Let me know if you'd like to be added to this org, and I will make it happen.

Thanks everyone for helping out with this and giving this software a good home.

**Comment by j15e** [comment]
Thanks for your contribution @jim & thanks to @gr8bit and @swcraig for taking over!

I don't need org access, I will open a PR if needed.

Best

**Comment by swcraig** [comment]
Thank you for this @jim.

Happy New Year all!
