### ISSUE TITLE
About the country code of Kosovo

### ISSUE THREAD

**Issue by Aiken00** [carmen-ruby/carmen#244]
The country code of Kosovo is KV in locale currently. However, most of the standards are XK for 2 letter code and UNK 3 letter code instead. Is this meaningful to change the code as a common standard, i.e. XK? 

And if I want to add this country for selection? Does that mean I have to add the code under `iso_data/overlay` ?

https://en.wikipedia.org/wiki/Kosovo
`XK is a "user assigned" ISO 3166 code not designated by the standard, but used by the European Commission, Switzerland, the Deutsche Bundesbank and other organisations.`

**Comment by swcraig** [comment]
Hi @Aiken00, thanks for opening this up.

KV is used in 8 of the overlay locales at the moment (`CS`, `DE`, `HI`, `JA`, `PL`, `PT`, `SK`, and `CN`).
I don't agree with this and believe that Carmen should only reflect country codes that are part of the actual ISO standard.

In the case that this is not preferable (and to answer your second question): while you could directly modify the YAML files that ship with Carmen, the [README outlines the preferred way to augment the data (like adding a new country for example)](https://github.com/carmen-ruby/carmen#overriding-structural-data).
