### ISSUE TITLE
Bahamas -> New Providence (BS-NP) island state  missing

### ISSUE THREAD

**Issue by perticascatalin** [carmen-ruby/carmen#280]
Based on this (https://en.wikipedia.org/wiki/ISO_3166-2:BS), there should be a Bahamas island state/district for New Providence.

**Comment by TecnoSigma** [comment]
HI,

I created the PR: https://github.com/carmen-ruby/carmen/pull/288

Tks!


Alexandre C Martins

**Comment by swcraig** [comment]
Thank you both!
